<?php

namespace Tests\Feature;

use App\Models\Document;
use App\Models\Source;
use App\Transformers\Types\PdfTransformer;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

class PdfTransformerTest extends TestCase
{

    public Document $document;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $source = Source::factory()
            ->webFileMetaData()
            ->create();

        $document = Document::factory()->create([
            'source_id' => $source->id,
            'guid' => 'example.pdf',
        ]);

        $from = base_path('tests/fixtures/example.pdf');

        if(!File::exists($document->pathToFile())) {
            File::makeDirectory(
                sprintf(storage_path('app/projects/%d/sources/%d'),
                    $source->project_id,
                    $source->id),
                0755,
                true
            );
            File::copy(
                $from,
                $document->pathToFile()
            );
        }

        $this->document = $document;
    }

    protected function tearDown(): void
    {
        if(!File::exists($this->document->pathToFile())) {
            File::delete($this->document->pathToFile());
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function test_gets_data_from_pdf()
    {

        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PdfTransformer($this->document);
        $transformer->handle();
        $this->assertDatabaseCount('document_chunks', 10);

    }

    public function test_does_not_repeat()
    {
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PdfTransformer($this->document);
        $transformer->handle();
        $this->assertDatabaseCount('document_chunks', 10);
        $transformer->handle();
        $this->assertDatabaseCount('document_chunks', 10);
    }

}
