<?php

namespace Tests\Feature;

use App\Models\Source;
use App\Source\Types\WebHook;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Mockery;
use Tests\TestCase;

class WebHookTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->markTestSkipped("@TODO generator made this and not ready yet to finish this part");
    }

    public function test_gets_file()
    {
        $webhook = get_fixture('github_webhook.json');

    }

    public function test_makes_document()
    {
        $source = Source::factory()->create();

        Storage::fake('projects');
        $webFileSourceType = new WebHook($source);

        Http::fake([
            'wikipedia.com/*' => Http::response('foo', 200),
        ]);

        $this->assertDatabaseCount('documents', 0);
        $webFileSourceType->handle();

        $this->assertDatabaseCount('documents', 1);

    }

    public function test_makes_document_once()
    {
        $source = Source::factory()->create();

        Storage::fake('projects');
        $webFileSourceType = new WebFile($source);

        Http::fake([
            'wikipedia.com/*' => Http::response('foo', 200),
        ]);

        $this->assertDatabaseCount('documents', 0);
        $webFileSourceType->handle();

        $this->assertDatabaseCount('documents', 1);
        $webFileSourceType->handle();
        $this->assertDatabaseCount('documents', 1);
    }

    protected function mockFunction($functionName, $returnValue)
    {
        $mock = Mockery::mock();
        $mock->shouldReceive('__invoke')->andReturn($returnValue);
        $this->app->instance($functionName, $mock);
    }
}
